import { geopoint, TagData } from './types';
import TinyCache from 'tinycache';
export declare const getTagnumberFromSlug: (inputText: string, fallback?: number, cache?: typeof TinyCache) => number;
export declare const getTagNumbersFromText: (inputText: string, fallback?: number | number[], cache?: typeof TinyCache) => number | number[];
export declare const getCreditFromText: (inputText: string, fallback?: string, cache?: typeof TinyCache) => string;
export declare const getFoundLocationFromText: (inputText: string, fallback: string, cache?: typeof TinyCache) => string;
export declare const getHintFromText: (inputText: string, fallback: string | string[], cache?: typeof TinyCache) => string | string[];
export declare const getGPSLocationFromText: (inputText: string, fallback: geopoint, cache?: typeof TinyCache) => geopoint;
export declare const getImgurAlbumIdFromText: (inputText: string, fallback: string, cache?: typeof TinyCache) => string;
export declare const getImageURLsFromText: (inputText: string, fallback: string | string[], cache?: typeof TinyCache) => string | string[];
export declare const getDiscussionUrlFromText: (inputText: string, cache?: typeof TinyCache) => string;
export declare const getImageHashFromText: (inputText: string, cache?: typeof TinyCache) => string;
export declare const getImgurFoundImageHashFromBikeTagData: (tag: TagData, cache?: typeof TinyCache) => string;
export declare const getImgurFoundDescriptionFromBikeTagData: (tag: TagData, cache?: typeof TinyCache) => string;
export declare const getImgurFoundTitleFromBikeTagData: (tag: TagData, cache?: typeof TinyCache) => string;
export declare const getImgurMysteryImageHashFromBikeTagData: (tag: TagData, cache?: typeof TinyCache) => string;
export declare const getImgurMysteryTitleFromBikeTagData: (tag: TagData, cache?: typeof TinyCache) => string;
export declare const getImgurMysteryDescriptionFromBikeTagData: (tag: TagData, cache?: typeof TinyCache) => string;
export declare const getBikeTagDescriptionFromData: (data: any) => string;
export declare const getBikeTagTitleFromData: (data: any) => string;
export declare const getBikeTagProofDescriptionFromData: (data: any) => string;
export declare const getBikeTagProofTitleFromData: (data: any) => string;
