import { AccessToken, ClientKey, SanityAccessToken, ImgurAccessToken, ImgurClientId, ImgurCredentials, SanityCredentials, SanityClientId, BikeTagCredentials, Payload } from './types';
import FormData from 'form-data';
export declare function isBase64(payload: string | Payload): boolean;
export declare function isImageUrl(payload: string | Payload): boolean;
export declare function isStream(payload: string | Payload): boolean;
export declare function createForm(payload: string | Payload): FormData;
export declare function isAccessToken(arg: unknown): arg is AccessToken;
export declare function isClientKey(arg: unknown): arg is ClientKey;
export declare function isSanityAccessToken(arg: unknown): arg is SanityAccessToken;
export declare function isSanityClientId(arg: unknown): arg is SanityClientId;
export declare function isImgurAccessToken(arg: unknown): arg is ImgurAccessToken;
export declare function isImgurClientId(arg: unknown): arg is ImgurClientId;
export declare function constructTagDataObject(data: any, fields?: never[]): any;
export declare function constructTagNumberSlug(number: number, game?: string): string;
export declare function isImgurCredentials(credentials: ImgurCredentials): boolean;
export declare function isSanityCredentials(credentials: SanityCredentials): boolean;
export declare function isBikeTagCredentials(credentials: BikeTagCredentials): boolean;
export declare function assignImgurCredentials(credentials: ImgurCredentials): ImgurCredentials;
export declare function assignSanityCredentials(credentials: SanityCredentials): SanityCredentials;
export declare function assignBikeTagCredentials(credentials: BikeTagCredentials): BikeTagCredentials;
export declare function getImgurPictures(): any[];
