export { deleteTag } from './deleteTag'
export { getGame } from './getGame'
export { getTag } from './getTag'
export { getTags } from './getTags'
export { updateTag } from './updateTag'
export { uploadTagImage } from './uploadTagImage'
