export { deleteTag } from './deleteTag'
export { getGameData } from './getGameData'
export { getTag } from './getTag'
export { getTags } from './getTags'
export { updateTag } from './updateTag'
export { uploadTagImage } from './uploadTagImage'
